- id: power_startup
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      payload: '1'
      topic: cmnd/sonoffs/restart
    service: mqtt.publish
  - data:
      payload: ''
      topic: cmnd/sonoffs/power
    service: mqtt.publish
  hide_entity: true
- id: '1540548760601'
  alias: BedRoomLightOff
  trigger:
  - entity_id: switch.sonoff_purple
    for: 00:05
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.bed_room_pir
    state: 'off'
  action:
  - data:
      entity_id: switch.sonoff_purple
    service: switch.turn_off