title: Town Square Apt 311
views:
  - id: 0
    title: Home
    cards:
      - id: 1
        type: glance
        title: Tracking
        columns: 3
        entities:
          - device_tracker.vicpobrv_moto
          - binary_sensor.bed_room_pir
          - binary_sensor.living_room_pir

      - id: 2
        type: glance
        title: Switches
        columns: 3
        entities:
          - entity: switch.sonoff_green
            tap_action: toggle
          - entity: switch.sonoff_purple
            tap_action: toggle
          - entity: switch.sonoff_white
            tap_action: toggle
      
      - type: horizontal-stack
        cards:
        - id: 3
          type: sensor
          entity: sensor.humidity
          graph: line
     
        - id: 4
          type: sensor
          entity: sensor.temperature
          graph: line

      - id: 5
        type: weather-forecast
        entity: weather.dark_sky